package by.epam.krein.abitapp.entity;

public enum Exam {
    CERTIFICATE,
    MATHEMATICS,
    RUSSIAN_LANGUAGE,
    BELARUSIAN_LANGUAGE,
    ENGLISH_LANGUAGE,
    SOCIAL_SCIENCE,
    BIOLOGY,
    CHEMISTRY,
    PHYSICS,
    WORLD_HISTORY,
    HISTORY_OF_BELARUS,
    GEOGRAPHY;
 }
